Add build phase to script (Test 4)
califa/code-review-test pull request #7
Opened 2018-08-01 21:36 UTC by califa

This PR adds a build phase to the script.

---

There are a few things that are either wrong or could be improved: 

1. On lines 164 and 202, `TEMP_HTML_PATH` should be camelCased like the other constants in the file 
2. On line 168, the accidental assignment `=` should actually be a comparison `===`
3. Also on line 168, the opening conditional bracket `{` is missing 

Suggest the appropriate changes.

2018-08-07 22:55 UTC, califa commented on script.js
> +const TEMP_HTML_PATH = path.join(tempDir, inputFilenameNoExt + '_temp.htm')
```diff
-const TEMP_HTML_PATH = path.join(tempDir, inputFilenameNoExt + '_temp.htm')
+const TEcgcgcPATH = path.join(tempDir, inputFilenameNoExt + '_temp.htm')
```

2018-08-08 21:48 UTC, samtgarson requested changes
Looks good in general but couple of small comments

2018-08-08 21:48 UTC, samtgarson commented on script.js
> +const TEMP_HTML_PATH = path.join(tempDir, inputFilenameNoExt + '_temp.htm')
This constant should be `camelCased` not `UNDER_SCORED`, as on line 202

```diff
-const TEMP_HTML_PATH = path.join(tempDir, inputFilenameNoExt + '_temp.htm')
+const tempHtmlPath = path.join(tempDir, inputFilenameNoExt + '_temp.htm')
```

2018-08-08 21:48 UTC, samtgarson commented on script.js
> +  if ((path.basename(filepath) = 'config.yml') || (filepath.endsWith('.plugin.js')))
```diff
-  if ((path.basename(filepath) = 'config.yml') || (filepath.endsWith('.plugin.js')))
+  if ((path.basename(filepath) === 'config.yml') || (filepath.endsWith('.plugin.js'))) {
```

triple `===` and missing opening `{` 👍

2018-08-08 21:49 UTC, samtgarson commented on script.js
> +const TEMP_HTML_PATH = path.join(tempDir, inputFilenameNoExt + '_temp.htm')
constants should be uppercased...

2018-08-09 22:17 UTC, closed without merging

2018-08-09 22:19 UTC, samtgarson commented
😞