Add build phase to script (Test 5)
califa/code-review-test pull request #8
Opened 2018-08-01 21:37 UTC by califa

This PR adds a build phase to the script.

---

There are a few things that are either wrong or could be improved: 

1. On lines 164 and 202, `TEMP_HTML_PATH` should be camelCased like the other constants in the file 
2. On line 168, the accidental assignment `=` should actually be a comparison `===`
3. Also on line 168, the opening conditional bracket `{` is missing 

Suggest the appropriate changes.

2018-08-08 23:23 UTC, jaredwy commented on script.js
> +  if ((path.basename(filepath) = 'config.yml') || (filepath.endsWith('.plugin.js')))
This line is missing a starting brace. 
```diff
-  if ((path.basename(filepath) = 'config.yml') || (filepath.endsWith('.plugin.js')))
+  if ((path.basename(filePath) = 'base.yml') || (filPath.endsWith('.test.js'))) {
```

2018-08-08 23:28 UTC, jaredwy commented on script.js
> +  if ((path.basename(filePath) = 'base.yml') || (filPath.endsWith('.test.js'))) {
```diff
-  if ((path.basename(filePath) = 'base.yml') || (filPath.endsWith('.test.js'))) {
+  if ((path.basename(filePath) = 'base.yml') || (filePath.endsWith('.test.js'))) {
```

2018-08-08 23:33 UTC, jaredwy requested changes

2018-08-08 23:33 UTC, jaredwy commented on script.js
> +  if ((path.basename(filePath) = 'base.yml') || (filPath.endsWith('.test.js'))) {
```diff
-  if ((path.basename(filePath) = 'base.yml') || (filPath.endsWith('.test.js'))) {
+  if ((path.basename(filePath) = 'base.yml') || (filPath.endsWith('.test.js'))) {
```

2018-08-08 23:33 UTC, jaredwy commented on script.js
> +  var taskPromise = null
```diff
-  var taskPromise = null
+  var taskPromise = {};
+  
```

2018-08-09 21:51 UTC, califa commented on script.js
> +  if (!(relaxedGlobals.watchedExtensions.some(ext => filepath.endsWith(ext)))) {
```diff
-  if (!(relaxedGlobals.watchedExtensions.some(ext => filepath.endsWith(ext)))) {
+  if (!(relaxedGlobals.wtensions.some(ext => filepath.endsWith(ext)))) {
```

2018-08-09 22:17 UTC, closed without merging